brew "neovim"
brew "powerlevel10k"
brew "tmux"
brew "zsh-syntax-highlighting"
brew "zsh-autosuggestions"

brew "bat"
brew "fd"
brew "fzf"
brew "gh"
brew "rcm"
brew "ripgrep"
brew "protobuf"
brew "ncdu"

tap "cormacrelf/tap"
brew "cormacrelf/tap/dark-notify"

tap "sourcegraph/src-cli"
brew "sourcegraph/src-cli/src-cli"
