brew "neovim"
brew "starship"
brew "powerlevel10k"
brew "tmux"
brew "zsh-syntax-highlighting"
brew "zsh-autosuggestions"

brew "bat"
brew "fd"
brew "fzf"
brew "git"
brew "rcm"
brew "ripgrep"
brew "protobuf"
brew "ncdu"

tap "cormacrelf/tap"
brew "cormacrelf/tap/dark-notify"
